apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: expense
    module: backend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx


---
apiVersion: apps/v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    name: labels
  ports:
  - Port: 80
    targetPort: 80

