apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: expense
    module: backend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: labels
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30009
