apiVersion: v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: ezy-index
          mountpath: /usr/share/nginx/html
    volumes:
    - name: ezy-index
      configMap:
        name: ezy-index