apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-quota
  namespace: dev-namespace
spec:
  hard:
    pods: "10"
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    persistentvolumeclaims: "5"
    requests.storage: 50Gi