apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim-1
  namespace: dev-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2

---





