apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: dev-namespace
spec:
  replicas: 11
  selector:
    matchLabels:
      app: test-nginx
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
        